---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: campusservice
  name: campusservice
  namespace: classns
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: health
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: campusservice
  type: ClusterIP