---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: campusservice
  name: campusservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: health
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: campusservice
  type: ClusterIP
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: campusservice
#   namespace: {{ .Values.namespace }}
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: campusservice
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50