---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notificationservice
  name: notificationservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: notificationservice
  type: ClusterIP
