apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-server-np
  name: argo-server-np
  namespace: argo
spec:
  ports:
  - name: http
    nodePort: 30000
    port: 2746
    protocol: TCP
    targetPort: 2746
  selector:
    app: argo-server
  type: NodePort