---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authservice
  name: authservice
  namespace: classns
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: authservice
  type: ClusterIP