---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authservice
  name: authservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: authservice
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authservice
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50