apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: socketservice
  labels:
    app: socketservice

spec:
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      name: socketservice
      labels:
        app: socketservice
    spec:
      containers:
      - name: socketservice
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: APP_NAME
          value: socketservice
        - name: KAFKA_URL
          value: "kafkasvc.classns-logging.svc.cluster.local:9092"
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: VAULT_ADDR
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: VAULT_ROLE_ID
        - name: VAULT_ROLE_SECRET
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: VAULT_ROLE_SECRET
        - name: ENV
          value: "prod"
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        ports:
        - name: http
          containerPort: 5050
      initContainers:
      - name: init-service
        image: docker.laniakea.local:8080/backend/tools:latest
        env:
        - name: APP_NAME
          value: socketservice
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: VAULT_ADDR
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: VAULT_ROLE_ID
        - name: VAULT_ROLE_SECRET
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: VAULT_ROLE_SECRET
      imagePullSecrets:
      - name: regsecret
      nodeSelector:
        application: upclass
  replicas: 1
  selector:
    matchLabels:
      app: socketservice
