---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: socketservice
  name: socketservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: socketservice
  type: ClusterIP