# Default values for class-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: classns-dev

image:
  registry: docker.laniakea.local:8080
  repository: backend/authservice
  pullPolicy: Always
  tag: latest


resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

