---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisservice
  name: redisservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redisservice
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisservice
  name: redisservicenp
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    nodePort: {{ .Values.redis_node_port }}
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redisservice
  type: NodePort