# Default values for class-content.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: classns-dev

image:
  registry: docker.laniakea.local:8080
  repository: backend/redisservice
  pullPolicy: Always
  tag: latest


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi