apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: monitoring
  namespace: argocd
spec:
  description: Core metrics 
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
--- 
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  type: helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus-stack
  namespace: argocd
spec: 
  project: monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.7.0
    helm:
      releaseName: prometheus-stack
      valuesObject:
        fullnameOverride: prometheus
        alertmanager:
          fullnameOverride: alertmanager
        grafana:
          fullnameOverride: grafana
  destination:
    server: https://192.168.254.201:6443
    namespace: classns-logging

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   selfHeal: false #set to true in prod