apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: registrysvc
  name: registrysvc
spec:
  type: ExternalName
  externalName: 8.8.8.8
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: kafkasvc
  name: kafkasvc
spec:
  type: ExternalName
  externalName: kafkasvc.{{ .Values.logs_namespace }}.svc.cluster.local
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: classdb
  name: classdb
spec:
  type: ExternalName
  externalName: dbservice.{{ .Values.core_namespace }}.svc.cluster.local
  ports:
  - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: logstash
  name: logstash
spec:
  type: ExternalName
  externalName: logstash.{{ .Values.logs_namespace }}.svc.cluster.local
  ports:
  - port: 5044
    protocol: TCP
    targetPort: 5044


