apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: keydbservice
  labels:
    app: keydbservice

spec:
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      name: keydbservice
      labels:
        app: keydbservice
    spec:
      containers:
      - name: keydbservice
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: APP_NAME
          value: keydbservice
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        ports:
        - name: http
          containerPort: 6379
      imagePullSecrets:
      - name: regsecret
      nodeSelector:	
        application: upclass
  replicas: 1
  selector:
    matchLabels:
      app: keydbservice
