---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keydbservice
  name: keydbservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: keydbservice
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keydbservice
  name: keydbservicenp
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    nodePort: 30620
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: keydbservice
  type: NodePort
