
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbservice
  name: dbservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: dbservice
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: classdbnp
  name: classdbnp
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    nodePort: {{ .Values.db_node_port }}
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: dbservice
  type: NodePort

---
# ---
# # Source: class-gw-ingress/templates/ingress.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: database-service-ingress
#   namespace: {{ .Values.namespace }}
#   labels:
#     app.kubernetes.io/name: nginx-ingress
#     app.kubernetes.io/part-of: nginx-ingress
# spec:
#   type: LoadBalancer
#   ports:
#     - name: mariadb
#       port: 3306
#       targetPort: 3306
#       protocol: TCP
#   selector:
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/part-of: ingress-nginx