apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: upclass-core-prd
  namespace: argocd
spec:
  description: Upclass core environment/shared service
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: class-db-prd
  namespace: argocd
spec: 
  project: upclass-core-prd
  source:
    chart: class-db
    repoURL: https://stalemartyr.github.io/helm-charts
    targetRevision: 1.0.3
    helm:
      releaseName: class-db-prd
      valuesObject:
        namespace: classns-core-prd
        volume:
          path: "/export/CLUSTER/database-prd"
  destination:
    server: https://192.168.254.201:6443
    namespace: classns-core-prd

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   selfHeal: false #set to true in prod