apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: upclass-core
  namespace: argocd
spec:
  description: Upclass core environment/shared service
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---