apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: upclass-core-prd
  namespace: argocd
spec:
  description: Upclass core environment/shared service
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: class-db-prd
  namespace: argocd
spec: 
  project: upclass-core-prd
  source:
    chart: class-db
    repoURL: https://stalemartyr.github.io/helm-charts
    targetRevision: 1.0.7
    helm:
      releaseName: class-db-prd
      valuesObject:
        namespace: classns-core-prd
        pv_name: "classdb-volume-prd"
        pvc_name: "classdb-volumeclaim-prd"
        db_node_port: 30604
        volume:
          server:
            path: "/export/CLUSTER/database-prd"
        class-auth:
          namespace: "classns-prd"
        class-courses:
          namespace: "classns-prd"
        class-campus:
          namespace: "classns-prd"
        class-content:
          namespace: "classns-prd"
        class-email:
          namespace: "classns-prd"
        class-enroll:
          namespace: "classns-prd"
        class-exam:
          namespace: "classns-prd"
        class-files:
          namespace: "classns-prd"
        class-messages:
          namespace: "classns-prd"
        class-notifications:
          namespace: "classns-prd"
        class-redis:
          namespace: "classns-prd"
        class-references:
          namespace: "classns-prd"
        class-socket:
          namespace: "classns-prd"
        class-user:
          namespace: "classns-prd"
  destination:
    server: https://192.168.254.201:6443
    namespace: classns-core-prd

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   selfHeal: false #set to true in prod