
namespace: classns-dev
core_namespace: classns-core
logs_namespace: classns-logging

class-auth:
  namespace: "classns-dev"
class-courses:
  namespace: "classns-dev"
class-campus:
  namespace: "classns-dev"
class-content:
  namespace: "classns-dev"
class-email:
  namespace: "classns-dev"
class-enroll:
  namespace: "classns-dev"
class-exam:
  namespace: "classns-dev"
class-files:
  namespace: "classns-dev"
  pv_name: file-volume
  pvc_name: file-volumeclaim
  server: 
    nfs: 
      server: nfs.laniakea.local
      path: /export/CLUSTER/uploads
class-messages:
  namespace: "classns-dev"
class-notifications:
  namespace: "classns-dev"
class-redis:
  namespace: "classns-dev"
  redis_node_port: 30610
class-references:
  namespace: "classns-dev"
class-socket:
  namespace: "classns-dev"
class-user:
  namespace: "classns-dev"
class-keydb:
  namespace: "classns-dev"
    #class-worker:
    #  namespace: "classns-dev"
