apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: nginx-ingress
  namespace: argocd
spec:
  description: Upclass core environment/shared service
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
--- 
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: metallb
  namespace: argocd
spec:
  description: Upclass core environment/shared service
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
--- 
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ingress
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: nginx-ingress
  url: ghcr.io/nginxinc
  enableOCI: "true"
  type: helm
--- 
apiVersion: v1
kind: Secret
metadata:
  name: metallb
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: metallb
  url: https://metallb.github.io/metallb
  type: helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nginx-ingress
  namespace: argocd
spec: 
  project: nginx-ingress
  source:
    chart: charts/nginx-ingress
    repoURL: ghcr.io/nginxinc
    targetRevision: 1.0.1
    helm:
      releaseName: nginx-ingress
      valuesObject:
        controller:
          name: "nginx-ingress"
          kind: "deployment"
          watchNamespace: "classns-dev"
          service:
            type: "LoadBalancer"
            httpPort:
              enable: true
              port: 80
            httpsPort:
              enable: true 
              port: 443
          ingressClass:
            name: "nginx-ingress"
  destination:
    server: https://192.168.254.201:6443
    namespace: nginx-ingress

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   selfHeal: false #set to true in prod
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: metallb
  namespace: argocd
spec: 
  project: metallb
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.10
    helm:
      releaseName: metallb
  destination:
    server: https://192.168.254.201:6443
    namespace: metallb-system

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   selfHeal: false #set to true in prod
    
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: metallbconfig
  namespace: argocd
spec: 
  project: metallb
  source: 
    repoURL: git@ssh.dev.azure.com:v3/upclassedu/upclass-app/helm-charts
    targetRevision: main
    path: lbconfig/dev
  destination:
    server: https://192.168.254.201:6443
    namespace: metallb-system

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   selfHeal: false #set to true in prod
