# Default values for class-content.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: classns-dev
upload_suffix: ""

image:
  registry: docker.laniakea.local:8080
  repository: backend/fileservice
  pullPolicy: Always
  tag: latest


pv_name: file-volume
pvc_name: file-volumeclaim
server: 
  nsf: 
    server: nfs.laniakea.local
    path: /export/CLUSTER/uploads


resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 128Mi